### PR TITLE
Improved CI - check fmt

### PR DESCRIPTION
**Pull request by alfonsorr**
Changed the scala setup plugin to a maintained action. Pipeline to check if the format is correct.
Added a cache to improve the speed in CI runs.
Updated checkout action to the latest version.

### CODE REVIEW

**Comment by alfonsorr** [comment]
@SemyonSinchenko @zeotuan I'm thinking of moving the benchmarking to the CI quality pipeline to run it only once and in parallel to speed up testing.

**Review by zeotuan — APPROVED** [review]
LGTM!

**Comment by zeotuan** [comment]
> @SemyonSinchenko @zeotuan I'm thinking of moving the benchmarking to the CI quality pipeline to run it only once and in parallel to speed up testing.

Sound good! Do you think we should still have benchmarks running for different version?

**Comment by alfonsorr** [comment]
Maybe have it for only one in the pr's or when merged and maybe in the release flow test against all of them. Not sure if testing against multiple versions will make a difference.

**Pull request merged**
