### PR TITLE
Add support for StructType columns in equality checks

### PR DESCRIPTION
**Pull request by reecedoyle**

### CODE REVIEW

**Comment by MrPowers** [comment]
@reecedoyle - Thanks for submitting this.  I am in Costa Rica at the moment.  Will take a close look when I'm back.  This is really needed!

**Comment by MrPowers** [comment]
@reecedoyle - thanks again for this contribution.  I'm sorry for the very late follow-up.  I completely forgot about this.

Can you refactor this code to add a `assertDeepSmallDatasetEquality` rather than change the behavior of the existing method?  I want to keep the existing method as performant as possible.  Let me know if that sounds alright to you!

**Comment by jckegelman** [comment]
Hello. Is there any way I can help move this PR along? It seems to provide the functionality I'm looking for.

**Comment by MrPowers** [comment]
@jckegelman - I dropped the ball on this one and don't work on Spark anymore, so in order to add this functionality, I'd probably need a new pull request with tons of tests.

Would need to show that the new functionality is 100% backwards compatible and isn't slow.  Let me know if you feel up for it 🤓

**Comment by zeotuan** [comment]
@MrPowers I need this feature. Gonna take a look

**Comment by zeotuan** [comment]
This is already supported in #97. I think we can close it

**Comment by SemyonSinchenko** [comment]
As @zeotuan the functionality is already supported.

**Pull request closed without merging**
