### PR TITLE
Publish to SonaType Central

### PR DESCRIPTION
**Pull request by zeotuan**

### CODE REVIEW

**Review by SemyonSinchenko — APPROVED** [review]

**Comment by zeotuan** [comment]
@SemyonSinchenko Recreated #178 as previous was stuck in processing for too long after force push

**Comment by alfonsorr** [comment]
The issue is due to the credentials. They are not  well setted

**Comment by zeotuan** [comment]
> The issue is due to the credentials. They are not well setted

It's one of my suspicions too. Will hold of this until we can update the username/password. We already verified that PGP passphrase and secret are correct

**Comment by zeotuan** [comment]
@alfonsorr @SemyonSinchenko Let's try using SonaType Central to release. We can always revert if it does not work

**Comment by alfonsorr** [comment]
> @alfonsorr @SemyonSinchenko Let's try using SonaType Central to release. We can always revert if it does not work

It won't be easy if @MrPowers gives us the url he used to get the credentials?

**Comment by zeotuan** [comment]
@alfonsorr  I was hoping we could quickly do a quick check by tagging to see if the release go through while waiting.

**Pull request merged**
