### PR TITLE
Update Spark/Scala Version, Feature enhancement

### PR DESCRIPTION
**Pull request by zeotuan**
- Support Spark 3.3 and 3.4
- Support tolerance for big decimal
- Support tolerance for nested row
- row compare performance improvement
- add benchmarking

### CODE REVIEW

**Comment by SemyonSinchenko** [comment]
@zeotuan Hello! Sorry for the long answer and thank you for the contribution. Any chance you can finish it / mark as "ready for review"?

**Comment by zeotuan** [comment]
@SemyonSinchenko No worries! Let me refine the branch before marking it as ready

**Comment by alfonsorr** [comment]
The contribution is great but I see too many things in one single pr. Could it be split to see better the focus of each new one of the functionalities?

**Comment by zeotuan** [comment]
> The contribution is great but I see too many things in one single pr. Could it be split to see better the focus of each new one of the functionalities?

Sure. I'll break it down into multiple PR

**Pull request closed without merging**
